# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'azure-container-registry'
    command: 'login'
# - task: Docker@2
#   inputs:
#     containerRegistry: 'azure-container-registry'
#     repository: 'example'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
#     tags: 'latest'
- task: HelmInstaller@0
  inputs:
    helmVersion: 'latest'
    installKubectl: true
    kubectlVersion: '1.19.0'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm --version 