apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: liferay
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: liferay-base
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "liferay:latest"
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: ./Dockerfile
      from:
        kind: "DockerImage"
        name: "liferay/dxp:7.2.10-dxp-7"



