apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }} 
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ .Values.name }}-svc 
    weight: 100
  wildcardPolicy: None
