apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP 
    targetPort: 8080
  selector:
    app: {{ .Values.name }}
