apiVersion: v1
kind: Service
metadata:
  labels:
    app: oracle-enterprise
  name: oracle-enterprise
spec:
  ports:
  - name: 1521-tcp
    port: 1521
    protocol: TCP
    targetPort: 1521
  - name: 5500-tcp
    port: 5500
    protocol: TCP
    targetPort: 5500
  selector:
    app: oracle-enterprise
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oracle-enterprise
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
  name: oracle-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-enterprise
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle-enterprise
    spec:
      containers:
      - image: oracle-enterprise:19.3.0.0
        name: oracle-enterprise
        ports:
        - containerPort: 1521
          protocol: TCP
        - containerPort: 5500
          protocol: TCP
        volumeMounts:
        - mountPath: /ORCL
          name: orcl
      restartPolicy: Always
      securityContext:
        fsGroup: 54321
      serviceAccount: oracle
      serviceAccountName: oracle
      imagePullPolicy: IfNotPresent
      volumes:
      - name: orcl
        emptyDir: {}
